apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask
          image: rahulb2180/spe_major_project_backend:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/mnt/data"
              name: model
      volumes:
        - name: model
          hostPath:
            path: "/mnt/data"
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007
